{
 "title": "Funds",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "Bridge Transactions",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "database": "db_63113",
     "dateTimeColDataType": "dt",
     "dateTimeType": "DATETIME64",
     "formattedQuery": "SELECT toUnixTimestamp(toStartOfMinute(dt)) * 1000 as t, count() FROM $table WHERE dt BETWEEN toDateTime64($from, 3) AND toDateTime64($to, 3) GROUP BY t ORDER BY t",
     "query": "SELECT\n    dt as \"Timestamp\",\n    message.event.topic_string as \"Method\",\n    message.txurl_string as \"Transaction\"\nFROM $table\n\nWHERE\n    dt BETWEEN toDateTime64($from, 3)\n    AND toDateTime64($to, 3)\n    AND message.topic_string = 'contractEvent'\n\nORDER BY dt desc\n",
     "rawQuery": "SELECT\n    dt as \"Timestamp\",\n    message.event.topic_string as \"Method\",\n    message.txurl_string as \"Transaction\"\nFROM db_63113.supplier_server_testnet_source\n\nWHERE\n    dt BETWEEN toDateTime64(1656692551, 3)\n    AND toDateTime64(1656693451, 3)\n    AND message.topic_string = 'contractEvent'\n\nORDER BY dt desc",
     "round": "0s",
     "table": "supplier_server_testnet_source"
    }
   ]
  },
  {
   "title": "Supplier Errors",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "database": "db_63113",
     "dateTimeColDataType": "dt",
     "dateTimeType": "DATETIME64",
     "formattedQuery": "SELECT toUnixTimestamp(toStartOfMinute(dt)) * 1000 as t, count() FROM $table WHERE dt BETWEEN toDateTime64($from, 3) AND toDateTime64($to, 3) GROUP BY t ORDER BY t",
     "query": "SELECT\n    dt,\n    message.msg_string,\n    message.level_integer\nFROM $table\n\nWHERE\n    dt BETWEEN toDateTime64($from, 3)\n    AND toDateTime64($to, 3)\n    AND message.level_integer > 30\n\nORDER BY dt desc\n",
     "rawQuery": "SELECT\n    dt,\n    message.msg_string,\n    message.level_integer\nFROM db_63113.supplier_server_testnet_source\n\nWHERE\n    dt BETWEEN toDateTime64(1656018613, 3)\n    AND toDateTime64(1656022213, 3)\n    AND message.level_integer > 30\n\nORDER BY dt desc",
     "round": "0s",
     "table": "supplier_server_testnet_source"
    }
   ]
  },
  {
   "title": "xBTC Funds",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "string" }
   ],
   "targets": [
    {
     "database": "db_63113",
     "dateTimeColDataType": "dt",
     "dateTimeType": "DATETIME64",
     "formattedQuery": "SELECT toUnixTimestamp(toStartOfMinute(dt)) * 1000 as t, count() FROM $table WHERE dt BETWEEN toDateTime64($from, 3) AND toDateTime64($to, 3) GROUP BY t ORDER BY t",
     "query": "SELECT\n    toUnixTimestamp(toStartOfMinute(dt)) * 1000 as t,\n    message.bridge_float as xbtc\nFROM $table\n\nWHERE\n    dt BETWEEN toDateTime64($from, 3)\n    AND toDateTime64($to, 3)\n    and message.topic_string = 'balances'\n\nORDER BY t\n",
     "rawQuery": "SELECT\n    toUnixTimestamp(toStartOfMinute(dt)) * 1000 as t,\n    message.bridge_float as xbtc\nFROM db_63113.supplier_server_testnet_source\n\nWHERE\n    dt BETWEEN toDateTime64(1656015984, 3)\n    AND toDateTime64(1656019584, 3)\n    and message.topic_string = 'balances'\n\nORDER BY t",
     "round": "0s",
     "table": "supplier_server_testnet_source"
    }
   ]
  },
  {
   "title": "STX",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "string" }
   ],
   "targets": [
    {
     "database": "db_63113",
     "dateTimeColDataType": "dt",
     "dateTimeType": "DATETIME64",
     "formattedQuery": "SELECT toUnixTimestamp(toStartOfMinute(dt)) * 1000 as t, count() FROM $table WHERE dt BETWEEN toDateTime64($from, 3) AND toDateTime64($to, 3) GROUP BY t ORDER BY t",
     "query": "SELECT\n    toUnixTimestamp(toStartOfMinute(dt)) * 1000 as t,\n    message.stx.stx_float\nFROM $table\n\nWHERE\n    dt BETWEEN toDateTime64($from, 3)\n    AND toDateTime64($to, 3)\n    and message.topic_string = 'balances'\n\nORDER BY t\n",
     "rawQuery": "SELECT\n    toUnixTimestamp(toStartOfMinute(dt)) * 1000 as t,\n    message.stx.stx_float\nFROM db_63113.supplier_server_testnet_source\n\nWHERE\n    dt BETWEEN toDateTime64(1656018932, 3)\n    AND toDateTime64(1656022532, 3)\n    and message.topic_string = 'balances'\n\nORDER BY t",
     "round": "0s",
     "table": "supplier_server_testnet_source"
    }
   ]
  },
  {
   "title": "BTC",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "database": "db_63113",
     "dateTimeColDataType": "dt",
     "dateTimeType": "DATETIME64",
     "formattedQuery": "SELECT toUnixTimestamp(toStartOfMinute(dt)) * 1000 as t, count() FROM $table WHERE dt BETWEEN toDateTime64($from, 3) AND toDateTime64($to, 3) GROUP BY t ORDER BY t",
     "query": "SELECT\n    toUnixTimestamp(toStartOfMinute(dt)) * 1000 as t,\n    message.btc.btc_float as btc\nFROM $table\n\nWHERE\n    dt BETWEEN toDateTime64($from, 3)\n    AND toDateTime64($to, 3)\n    and message.topic_string = 'balances'\n\nORDER BY t\n",
     "rawQuery": "SELECT\n    toUnixTimestamp(toStartOfMinute(dt)) * 1000 as t,\n    message.btc.btc_float as btc\nFROM db_63113.supplier_server_testnet_source\n\nWHERE\n    dt BETWEEN toDateTime64(1656015996, 3)\n    AND toDateTime64(1656019596, 3)\n    and message.topic_string = 'balances'\n\nORDER BY t",
     "round": "0s",
     "table": "supplier_server_testnet_source"
    }
   ]
  },
  {
   "title": "BTC Transactions",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 23 },
   "targets": [
    {
     "database": "db_63113",
     "dateTimeColDataType": "dt",
     "dateTimeType": "DATETIME64",
     "formattedQuery": "SELECT toUnixTimestamp(toStartOfMinute(dt)) * 1000 as t, count() FROM $table WHERE dt BETWEEN toDateTime64($from, 3) AND toDateTime64($to, 3) GROUP BY t ORDER BY t",
     "query": "SELECT\n    dt,\n    message.txurl_string,\n    message.txid_string\n    \nFROM $table\n\nWHERE\n    dt BETWEEN toDateTime64($from, 3)\n    AND toDateTime64($to, 3)\n    AND message.topic_string = 'btcBroadcast'\n\nORDER BY dt desc\n",
     "rawQuery": "SELECT\n    dt,\n    message.txurl_string,\n    message.txid_string\n    \nFROM db_63113.supplier_server_testnet_source\n\nWHERE\n    dt BETWEEN toDateTime64(1656019297, 3)\n    AND toDateTime64(1656022897, 3)\n    AND message.topic_string = 'btcBroadcast'\n\nORDER BY dt desc",
     "round": "0s",
     "table": "supplier_server_testnet_source"
    }
   ]
  },
  {
   "title": "BTC Transactions",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 32 },
   "targets": [
    {
     "database": "db_63113",
     "dateTimeColDataType": "dt",
     "dateTimeType": "DATETIME64",
     "formattedQuery": "SELECT toUnixTimestamp(toStartOfMinute(dt)) * 1000 as t, count() FROM $table WHERE dt BETWEEN toDateTime64($from, 3) AND toDateTime64($to, 3) GROUP BY t ORDER BY t",
     "query": "SELECT\n    dt,\n    round(message.amount_integer / 100000000, 8) as Amount,\n    message.recipient_string as Recipient\n    \nFROM $table\n\nWHERE\n    dt BETWEEN toDateTime64($from, 3)\n    AND toDateTime64($to, 3)\n    AND message.topic_string = 'sendBtc'\n\nORDER BY dt desc\n",
     "rawQuery": "SELECT\n    dt,\n    round(message.amount_integer / 100000000, 8) as Amount,\n    message.recipient_string as Recipient\n    \nFROM db_63113.supplier_server_testnet_source\n\nWHERE\n    dt BETWEEN toDateTime64(1655980181, 3)\n    AND toDateTime64(1656023381, 3)\n    AND message.topic_string = 'sendBtc'\n\nORDER BY dt desc",
     "round": "0s",
     "table": "supplier_server_testnet_source"
    }
   ]
  },
  {
   "title": "Log Messages",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 41 },
   "targets": [
    {
     "database": "db_63113",
     "dateTimeColDataType": "dt",
     "dateTimeType": "DATETIME64",
     "formattedQuery": "SELECT toUnixTimestamp(toStartOfMinute(dt)) * 1000 as t, count() FROM $table WHERE dt BETWEEN toDateTime64($from, 3) AND toDateTime64($to, 3) GROUP BY t ORDER BY t",
     "query": "SELECT\n    dt,\n    message.msg_string as Message\n    \nFROM $table\n\nWHERE\n    dt BETWEEN toDateTime64($from, 3)\n    AND toDateTime64($to, 3)\n    AND message.msg_string is not null\n    AND message.topic_string != 'balances'\n\nORDER BY dt desc\n",
     "rawQuery": "SELECT\n    dt,\n    message.msg_string as Message\n    \nFROM db_63113.supplier_server_testnet_source\n\nWHERE\n    dt BETWEEN toDateTime64(1656601687, 3)\n    AND toDateTime64(1656688087, 3)\n    AND message.msg_string is not null\n    AND message.topic_string != 'balances'\n\nORDER BY dt desc",
     "round": "0s",
     "table": "supplier_server_testnet_source"
    }
   ]
  }
 ]
}